services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/web/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
  
  db:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: dev_db
    volumes:
      - mongo_data:/data/db
    
volumes:
  mongo_data: